### ISSUE TITLE
benq projector W1000 hoping you can help

### ISSUE THREAD

**Issue by ajd-tech** [rrooggiieerr/benqprojector.py#3]
aj@gerrard:~$ python3 -m benqprojector /dev/ttyS0 9600 status
Unexpected response format, response: illegal format
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/__main__.py", line 35, in <module>
    if not projector.connect():
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 169, in connect
    model = self._send_command("modelname")
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 367, in _send_command
    raise InvallidResponseError(command, action, response)
benqprojector.benqprojector.InvallidResponseError: ('modelname', '?', 'illegal format')
aj@gerrard:~$ python3 -m benqprojector /dev/ttyS0 9600 examine
Unexpected response format, response: illegal format
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/__main__.py", line 35, in <module>
    if not projector.connect():
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 169, in connect
    model = self._send_command("modelname")
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 367, in _send_command
    raise InvallidResponseError(command, action, response)
benqprojector.benqprojector.InvallidResponseError: ('modelname', '?', 'illegal format')

**Comment by rrooggiieerr** [comment]
Hi! could you use the `--debug` argument on the command you're using for some more details?

**Comment by ajd-tech** [comment]
> Hi! could you use the `--debug` argument on the command you're using for some more details?

~$ python3 -m benqprojector /dev/ttyS0 9600 examine --debug
2023-01-14 10:54:59,359 DEBUG    command *modelname=?#
2023-01-14 10:54:59,384 DEBUG    Response: *modelname=?#
2023-01-14 10:54:59,384 DEBUG    Command successfully send
2023-01-14 10:54:59,410 DEBUG    Response: Illegal format
2023-01-14 10:54:59,410 DEBUG    LC Response: illegal format
2023-01-14 10:54:59,411 DEBUG    Raw response: 'illegal format'
2023-01-14 10:54:59,411 ERROR    Unexpected response format, response: illegal format
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/__main__.py", line 35, in <module>
    if not projector.connect():
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 169, in connect
    model = self._send_command("modelname")
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 367, in _send_command
    raise InvallidResponseError(command, action, response)
benqprojector.benqprojector.InvallidResponseError: ('modelname', '?', 'illegal format')

**Comment by rrooggiieerr** [comment]
Which model do you have?

**Comment by ajd-tech** [comment]
I have the w1000

**Comment by rrooggiieerr** [comment]
The W1000 manual says the RS-232 port (serial port) is there to update or download the projector’s firmware. It doesn't mention it's there to control the projector.

Can you connect to the projector with a terminal and control it with commands?

Instructions:
https://esupportdownload.benq.com/esupport/Projector/Control%20Protocols/PU9530/RS232%20Control%20Guide_0_Windows7_Windows8_WinXP.pdf

**Comment by ajd-tech** [comment]
I can connect to it with terminal, I am having issues formatting the serial write command to get a proper response in python.
I think most commands, work in terminal, although I don't think the modelname is working
_command_status = "*pow=?#"

ser.write(f"\r{_command_status}".encode('ascii'))

**Comment by pkoevesdi** [comment]
I suggest, try it first with a direct serial connection and a serial terminal program, before trying it in python or with this library here.

**Comment by ajd-tech** [comment]
Sorry, I guess i wasn't clear. I have the On, off, Status and Lamp hours working in a terminal program. MY problem is when I am sending the information over in Python seems to be a issue of how I am sending it.

Thanks

**Comment by pkoevesdi** [comment]
Ok, you say "On, off, Status and Lamp hours working in a terminal program" and "I don't think the modelname is working"... is the modelname not working from python or terminal? And in https://github.com/rrooggiieerr/benqprojector.py/issues/3#issuecomment-1383073514 you tell us a command, but what's the result?
So, please send the modelname command in terminal and tell the result and please tell the result from the python script with commands that are proved to work in the terminal.

**Comment by ajd-tech** [comment]
On, Off, power status and Lamp hours all work in the terminal(TeraTerm), model name Does not, I have Not got anything to work in Python with the command in [#3 (comment)](https://github.com/rrooggiieerr/benqprojector.py/issues/3#issuecomment-1383073514). I get nothing but illegal format from Python.

Below is the output from TeraTerm.
>
>*pow=on#
*POW=ON#
>*
>*pow=?#
[*POW=ON#](url)
>
>*ltim=?#
*LTIM=6706#
>*modelname=?#
Illegal format

**Comment by rrooggiieerr** [comment]
Hmm, just an other BenQ projector which doesn't follow their own documentation.

Do you get a prompt `>` in teraterm?

What happens if you try some other formats for modelname, like
```
*modelname=?
modelname=?#
*modelname?#
*modelname=#
*model=?#
```

Or other variants on the above

**Comment by ajd-tech** [comment]
I have tried the following, with all reporting Illegal format. Anyway you can make a version removing the Model check or point me in the direction to modify.

*model=?#
*modelname=?
modelname=?
modelname=?#
*modelname=?
model=?#
*modelname=?
modelname=?
*modelnam=?#

**Comment by rrooggiieerr** [comment]
I released a new version today where modelname is not mandatory, could you give that one a try?

**Comment by ajd-tech** [comment]
Thanks for making changes

I reinstalled in both HA and the pip on my test system and go the the following. Did I not get the latest ver

~$ python3 -m benqprojector /dev/ttyS0 9600 status --debug
2023-01-20 17:04:07,332 DEBUG    command *modelname=?#
2023-01-20 17:04:07,358 DEBUG    Response: *modelname=?#
2023-01-20 17:04:07,358 DEBUG    Command successfully send
2023-01-20 17:04:07,384 DEBUG    Response: Illegal format
2023-01-20 17:04:07,384 DEBUG    LC Response: illegal format
2023-01-20 17:04:07,385 DEBUG    Raw response: 'illegal format'
2023-01-20 17:04:07,385 ERROR    Unexpected response format, response: illegal format
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/__main__.py", line 35, in <module>
    if not projector.connect():
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 169, in connect
    model = self._send_command("modelname")
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 367, in _send_command
    raise InvallidResponseError(command, action, response)
benqprojector.benqprojector.InvallidResponseError: ('modelname', '?', 'illegal format')

**Comment by rrooggiieerr** [comment]
Looks like you're still using an old version of the lib

**Comment by ajd-tech** [comment]
uninstalled the old pip package 0.0.10 you can see below and installed 0.0.12. 

I am still getting the same results

d:~$ python -m benqprojector /dev/ttyS0 9600 status --debug
2023-01-21 11:09:46,180 DEBUG    command *modelname=?#
2023-01-21 11:09:46,254 DEBUG    Response: *Illegal forma
2023-01-21 11:09:46,255 DEBUG    No command echo received
2023-01-21 11:09:46,255 DEBUG    LC Response: *illegal forma
2023-01-21 11:09:46,255 DEBUG    Raw response: '*illegal forma'
2023-01-21 11:09:46,255 ERROR    Unexpected response format, response: *illegal forma
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/__main__.py", line 38, in <module>
    if not projector.connect():
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 210, in connect
    model = self._send_command("modelname")
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 374, in _send_command
    return self._parse_response(command, action, _command, response)
  File "/home/aj/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 430, in _parse_response
    raise InvallidResponseError(command, action, response)
benqprojector.benqprojector.InvallidResponseError: ('modelname', '?', '*illegal forma')








d:~/benq/benqprojector.py-main/benqprojector$ pip3 uninstall benqprojector
Found existing installation: benqprojector 0.0.10
Uninstalling benqprojector-0.0.10:
  Would remove:
    /home/aj/.local/lib/python3.10/site-packages/benqprojector-0.0.10.dist-info/*
    /home/aj/.local/lib/python3.10/site-packages/benqprojector/*
Proceed (Y/n)? Y
  Successfully uninstalled benqprojector-0.0.10
aj@gerrard:~/benq/benqprojector.py-main/benqprojector$ pip3 install benqprojector
Defaulting to user installation because normal site-packages is not writeable
Collecting benqprojector
  Downloading benqprojector-0.0.12-py3-none-any.whl (17 kB)
Requirement already satisfied: pyserial>=3.4 in /usr/lib/python3/dist-packages (from benqprojector) (3.5)
Installing collected packages: benqprojector
Successfully installed benqprojector-0.0.12

**Comment by rrooggiieerr** [comment]
Can you give me the **exact** communication you get when you execute the command in teraterm? Maybe a screenshot can't copy/paste the communication.

**Comment by ajd-tech** [comment]
I will get you the screen shot.

in the mean time in my attempt to write a integration I got this code to work

_command_init ="\r"
_command_on =  "*pow=on#\r"
_command_status = "*pow=?#\r"
_command_model = "*model=?#\r"
_command_lamp = "*ltim=?#\r"

ser.write(_command_init.encode())
time.sleep(1)
resp = ser.readline(1) #Read from Serialport
print("Recv:  ",resp)
if resp != b">":
  print(" Invalid response, check cable")
  ser.flush
  ser.close()
  raise SystemExit
ser.flush()

print('Command String to send:  ' )

time.sleep(0.5)
# had to  make sure the ">' was up when the next command was sent
ser.write(_command_init.encode())
ser.write(_command_staus.encode())
# let's wait one second before reading output (let's give device time to answer)
time.sleep(1)
while ser.inWaiting() > 0:
    resp += ser.read(1)
if resp != '':
    resp = resp.strip(b"\x00")
    resp = resp.decode()
    print(resp)

ser.close()

**Comment by rrooggiieerr** [comment]
That looks a lot like the commands I'm doing in the library. Look at line 209 and onwards of `benqprojector.py`. That's where it goes wrong with your projector

**Comment by ajd-tech** [comment]
Forked your code Made some generic code changes and please fee free to send suggestions.

**Comment by rrooggiieerr** [comment]
I'm trying to understand what you want to accomplish with your changes.

You modified the method `_wait_for_prompt()`. Did you have a problem with the command prompt not being retrieved? Since you removed the time-out check, the code can potentially wait indefinitely making the library, and thus the HA integration freeze. What's the use of the `readtry` variable?

I don't really see how it improved the existing code, except for maybe the hard coded timeout of 1 second which was maybe too short for you? In that case I would suggest to increase the timeout or read the timeout from a variable which can then be configured.

Further you add the command echo to the `previous_response` variable, and later validate the response using
```
                 if previous_response + response == "*modelname=?#Illegal format":
                        response = "*MODELNAME=W1000#"
```
I think you're trying to work around the fact that your projector doesn't support the `modelname` command.

It is not known if only the W1000 model is not supporting the `modelname` command, or if there are other models which also don't support the command. Hardcoding the modelname is not the prettiest solution in my opinion and can also break support for other models.

The existing code from line 209 onwards already takes into consideration if the `modelname` command is not supported:
```
        model = None
        try:
            model = self._send_command("modelname")
            assert model is not None, "Failed to retrieve projector model"
        except IllegalFormatError:
            # W1000 does not seem to return project model, but gives an illegal
            # format error. Maybe there are other models with the same problem?
            logger.error("Unable to retrieve projector model")
        except BlockedItemError:
            # Is projector powering down?
            logger.error(
                "Unable to retrieve projector model, is projector powering down?"
            )
            raise
        self.model = model
```

**Comment by ajd-tech** [comment]
All of what your saying is true, except when I run the code the code from 209 onward just fails it still doesn't allow for the code to continue and use ON, OFF, STATUS, LAMP hours. 

I was hoping this might trigger or help lead to a better solution. Sorry its been years since I really coded and just learning python. It's been good in that way.

**Comment by rrooggiieerr** [comment]
Try to find out on what line the code breaks by adding extra `logger.debug` lines in the code

**Comment by ajd-tech** [comment]
OK So i took out all my CRAP and this everything looks good up until I get this error (I suspect that benqprojector.configs should be just configs)

Exception has occurred: ModuleNotFoundError
No module named 'benqprojector.configs'; 'benqprojector' is not a package
AttributeError: module 'benqprojector' has no attribute '__path__'

During handling of the above exception, another exception occurred:

  File "C:\Users\aj\Documents\benqprojector.py-main\benqprojector.py-main\benqprojector\benqprojector.py", line 224, in connect
    with importlib.resources.open_text("benqprojector.configs", "all.json") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aj\Documents\benqprojector.py-main\benqprojector.py-main\benqprojector\__main__.py", line 41, in <module>
    if not projector.connect():
           ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'benqprojector.configs'; 'benqprojector' is not a package

**Comment by rrooggiieerr** [comment]
This looks familiar to me, and should've been fixed with the commit of Jan 20th https://github.com/rrooggiieerr/benqprojector.py/commit/c6906932373cdaf7323dd869f5e7a5069648a315

**Comment by rrooggiieerr** [comment]
How are you executing your code?

Being in te source root and executing `python3 -m benqprojector` should be the right way. If you're in the source root and execute `python3 ./benqprojector` this could go wrong.

Also make sure you have any previous installed versions of the library uninstalled:
```
pip uninstall benqprojector
```

**Comment by ajd-tech** [comment]
Everything is running now
Now just to get it to update in HA

Thanks,
